### ISSUE TITLE
有没有大佬帮忙解答一下，感激不尽

### ISSUE THREAD

**Issue by fjycomes** [MiracleTanC/Neo4j-KGBuilder#53]
2023-09-04 15:46:00.727 ERROR 8412 --- [  restartedMain] com.warmer.base.util.Neo4jUtil           : There is no procedure with the name `apoc.meta.stats` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

**Comment by MiracleTanC** [comment]
先安装apoc
https://neo4j.com/docs/apoc/current/introduction/

> 2023-09-04 15:46:00.727 ERROR 8412 --- [ restartedMain] com.warmer.base.util.Neo4jUtil : There is no procedure with the name `apoc.meta.stats` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

**Comment by fjycomes** [comment]
> 先安装apoc https://neo4j.com/docs/apoc/current/introduction/
> 
> > 2023-09-04 15:46:00.727 ERROR 8412 --- [ restartedMain] com.warmer.base.util.Neo4jUtil : There is no procedure with the name `apoc.meta.stats` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
安装好了，已经不会报错了， 感谢大佬

**Comment by MiracleTanC** [comment]
resolve
